# Github Actions workflow to build the base image
name: Build Base Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build base image
        run: docker build -t base-image ./docker_image

      - name: Push base image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag base-image ghcr.io/${{ github.repository }}/base-image:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/base-image:${{ github.ref_name }}
      
      # if branch is main, also push as latest
      - name: Push base image as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag base-image ghcr.io/${{ github.repository }}/base-image:latest
          docker push ghcr.io/${{ github.repository }}/base-image:latest